version: '3.8'

services:
  birthday_service:
    build: .
    container_name: vk_to_tg_birthday
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=Europe/Moscow
    command: ["python", "-m", "src.birthday_module"]

  event_service:
    build: .
    container_name: vk_to_tg_event
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=Europe/Moscow
    command: ["python", "-m", "src.event_module"]